### ISSUE TITLE
Outflow file with a single z=0

### ISSUE THREAD

**Issue by adrien-ga** [Eawag-AppliedSystemAnalysis/Simstrat#10]
Simstrat seems to crash (invalid memory reference) if the file containing outflow values has only two columns (one for time and one for outflow) and the outflow is given at z=0.

**Comment by adrien-ga** [comment]
Crash (this time erroneous arithmetic operation) also observed if there are several columns (i.e. outflow depths), but the last one is at 0m.
Maybe this happens because the lake level goes below 0m and therefore Simstrat does not know how to understand the outflow at 0m...
This seems to be a new bug with the newest versions of Simstrat 1.4. I don't think this happened before, as my code was running normally before I updated the exe file...

**Comment by Diftin** [comment]
These problems do not seem to arise in version 2.0.
