### ISSUE TITLE
Error in bathymetry file

### ISSUE THREAD

**Issue by adrien-ga** [Eawag-AppliedSystemAnalysis/Simstrat#11]
The model diverges and crashes if there is an anomaly in the bathymetry file (e.g. one area that is smaller at a shallower depth). A warning/error should be issued.

**Comment by Diftin** [comment]
I introduced a warning. I noticed that the code crashes at some point if you go on. I don't know if there is a realistic scenario involving a smaller area at a shallower depth.. so I would go deeper into this once there is a need.
