### ISSUE TITLE
Feature request: progress indicator

### ISSUE THREAD

**Issue by zimmermm** [Eawag-AppliedSystemAnalysis/Simstrat#13]
It would be nice to have some kind of progress indication.
This is not too hard to implement. Either using a fancy existing library: https://github.com/szaghi/forbear
Or by a simple write with no-advance statement.

**Comment by Diftin** [comment]
The no-advance statement does not work if you print the results at the same time, right?

We can implement it for the next version with the fancy library :)

**Comment by d-vanzo** [comment]
see merge #22 
I think the issue is resolved
