### ISSUE TITLE
Handling of line return

### ISSUE THREAD

**Issue by adrien-ga** [Eawag-AppliedSystemAnalysis/Simstrat#18]
Simstrat seems not to handle files with only "carriage return" \r and seems to require "carriage return + line feed" \r\n
Issue seen in v1.6: Simstrat sees the inflow/outflow files as empty and disables the advection calculation, resulting in totally ignoring inflow and outflows. No warning whatsoever!

From Stackoverflow:
\r = CR (Carriage Return)   Used as a new line character in Mac OS before X
\n = LF (Line Feed)             Used as a new line character in Unix/Mac OS X
\r\n = CR + LF                    Used as a new line character in Windows

**Comment by Diftin** [comment]
There is a warning now if advection is disabled. It also asks the user to verify the line feed in case his inflow files are not empty but he still gets "advection disabled". I think we can not do more here than to ask the user to have inflow files with the right line feed.
