### ISSUE TITLE
test dev/progressbar branch

### ISSUE THREAD

**Issue by d-vanzo** [Eawag-AppliedSystemAnalysis/Simstrat#25]
for *WINDOWS* developers... can you build and test the `dev/progressbar` feature?
The building should be smooth and easy using FoBiS as usual if you have Python 2.X, while it should not work with Python 3.X

I cannot test because I do not have a WIN building env...
thanks!

**Comment by Diftin** [comment]
I confirm that compilation does not work under windows with Python 3.6.1. Maybe someone who is working with Python 2 can confirm that it works?

**Comment by Diftin** [comment]
The problem is linked to FoBiS (which is currently used as a build system) encoding issues under windows. I changed the encoding in FoBiS and I am now able to successfully compile forbear. However, I would like to wait with merging this branch into the master until the changes are officially integrated into FoBiS.

**Comment by d-vanzo** [comment]
I had a look to @Diftin pull request in FoBis repo... the problem is that your modifications are compatible with Python 3.X, but not back compatible with Python 2.X in the present form. (btw FoBiS is designed for Python 2.X)

**Comment by Diftin** [comment]
Ok thanks. Do you have a suggestion to be compatible with python 2? Or should I just check for the version before specifying the encoding? Then progressbar would only work for python 3.

**Comment by d-vanzo** [comment]
there are several strategies, as example [here](https://stackoverflow.com/questions/10971033/backporting-python-3-openencoding-utf-8-to-python-2).

Or maybe adding something like this in ` src/main/python/fobis/ParsedFile.py`
`
import sys
def openFile(filename):
    if sys.version_info[0] < 3:   
        return open(filename, 'r')
   else:
        return open(filename, 'r', newline='', encoding='utf8')
`

this might work...

**Comment by d-vanzo** [comment]
@Diftin the fobis module has been updated to version `2.9.7`... can you give a try if this solve the issue with Windows compiling? (you have to upgrade the module with `pip (or pip3) install FoBiS.py --upgrade`

**Comment by Diftin** [comment]
The updated version does not solve the issue unfortunately.

**Comment by d-vanzo** [comment]
I just had a look and I'll push a new merge request soon... to zaghi repo

**Comment by Diftin** [comment]
The merge request seems really similar to what we tried last time (but failed the unittest).

**Comment by d-vanzo** [comment]
yes, I think was a really stupid missing `import sys` in the wrong position... let's see if szaghi accepts soon

**Comment by Diftin** [comment]
Ok true, this was the only change to the previous version that I could see.

**Comment by Diftin** [comment]
The new FoBiS release is out and the progressbar is now fully functional on the master branch.
