### ISSUE TITLE
prebuilt binaries with intel fortran compiler

### ISSUE THREAD

**Issue by zimmermm** [Eawag-AppliedSystemAnalysis/Simstrat#27]

**Comment by d-vanzo** [comment]
why would you need this? (i.e. why the gfortran version is not enough?)

**Comment by zimmermm** [comment]
because the code runs significantly faster when compiled with the intel compiler

**Comment by d-vanzo** [comment]
Yeah, in general Intel one produces slightly/moderately faster exec, I agree.
But if the difference is considerable maybe it is because of the optimization flag (in the fobos file Gnu is set to -O2, while Intel to -O3)...
Have you tested gnu compiler with -O3 (or -Ofast even)?

**Comment by zimmermm** [comment]
yeah, intel is still faster

**Comment by zimmermm** [comment]
hmm.. but maybe this will be a licence issue then?

**Comment by d-vanzo** [comment]
> hmm.. but maybe this will be a licence issue then?

Good point. I guess yes, it might be not legal to do it.
