### ISSUE TITLE
t0 omitted from solution in version 2.x

### ISSUE THREAD

**Issue by zimmermm** [Eawag-AppliedSystemAnalysis/Simstrat#31]
Is there a specific reason that t0 is omitted from the solution (i.e. output) in version 2.x?
For postprocessing, it would be easier if t0 is provided otherwise one has to read the solution AND interpolate the initial condition to get a full solution.

**Comment by Diftin** [comment]
No, there is no specific reason. I will change this.

**Comment by Diftin** [comment]
Problem solved on master.
