### ISSUE TITLE
All variables are written to file, even when specified not to

### ISSUE THREAD

**Issue by jorritmesman** [Eawag-AppliedSystemAnalysis/Simstrat#36]
I'm trying to have Simstrat write only water temperature to a file. However, when I change the settings in Output (in the par file) "All" to "false" and "Variables" to ["T"], still all variables are written to file.

`"All"   : false,
"Variables" : ["T"]`

I also tried `["T", "S", "WaterH"]`, but with the same result. Am I doing something wrong with the syntax, or is this feature not yet working?

Thanks!

**Comment by Diftin** [comment]
Hi Jorrit,
This feature is currently only on the master branch and not implemented in any release. So if you are using Simstrat 2.2, this feature unfortunately will not work.

**Comment by jorritmesman** [comment]
Okay, I didn't know that. Thanks for specifying!
