### ISSUE TITLE
[ERROR] Negative heat flux not allowed for melting

### ISSUE THREAD

**Issue by jorritmesman** [Eawag-AppliedSystemAnalysis/Simstrat#39]
I'm getting the error message "Negative heat flux not allowed for melting", when simulating a lake with (large amounts) of ice cover. In the lake, ice thickness can reach to about 50 cm. Some colleagues had exactly the same error in other lakes with ice cover when using Simstrat. The executable I used is the 2.4 Windows executable from this github, using forcing mode 3 (with precipitation and snow module on).

In my simulation, I start in January and the first winter ice cover forms and all looks normal. In the second winter, I get the error (ice forms before the model crashes). My colleagues also said that the error occurs somewhere in the middle of the simulation.

The forcing data that I use has worked in other models, and as far as I could see it should be working for Simstrat. Is this a bug, or am I doing something wrong? I can send my setup, if needed.

**Comment by Diftin** [comment]
This issue was solved with the bug fix version 2.4.1. See here for the new version: [https://github.com/Eawag-AppliedSystemAnalysis/Simstrat/releases/tag/v2.4.1](url)
