### ISSUE TITLE
Instructions on how to use simulations-snapshot feature

### ISSUE THREAD

**Issue by tadhg-moore** [Eawag-AppliedSystemAnalysis/Simstrat#42]
In v2.4 release there is a feature to start a simulation from a binary file. I am interested in applying Simstrat in a forecasting framework and would like to be able to utilise this feature to integrate into our data assimilation protocol. Can you provide instructions on how to use this feature? What exactly is stored within the binary file and if it is possible to extract and/or update the model states?

**Comment by Diftin** [comment]
Hi Tadhg,

This feature was coded by a software engineer who worked on Simstrat for a few weeks. To be sure that all necessary variables are stored for the restart, he essentially threw every variable available during a simulation into this binary. 
In the Simstrat main file, you see (lines 275-279) that there are 5 functions in different modules which save variables. You can then check in the individual modules (simdata, grid, absorption, lateral and output) what exactly is saved. For example, in simdata lines 295-344 show which variables are saved for this module.

I think you can read/write this binary file externally (outside of Simstrat), but I am not sure whether it is really more useful for your application than just the "normal" way of starting a Simstrat simulation (i.e. writing initial condition and inflow files).

Hope this helps but don't hesitate to get back to me if you need more information,
Fabian

**Comment by f-baerenbold** [comment]
Do you need more information or can I close this issue?

**Comment by tadhg-moore** [comment]
Thanks for the indepth information. I will be returning to this project soon but I think I have a clearer idea now from your answer so I think you can close the issue. If anything further comes up I will ask again. Cheers

**Comment by f-baerenbold** [comment]
Ok, just contact me by email (can be found on the eawag website) if you have further questions on this subject.
