### ISSUE TITLE
Submodule initialization

### ISSUE THREAD

**Issue by robertladwig** [Eawag-AppliedSystemAnalysis/Simstrat#48]
When trying to compile Simstrat on Ubuntu 20.04, I get the error that Forbear is referring to an unavailable Hash ID 24d1747e8da40c91037d6e72445a573c85748af9. 
```
(base) robert@wintergarten:~/Projects/AEMONJ/LER-WQ/Simstrat-AED/Simstrat$ ./git_lib_initialize.sh

Synchronizing submodule url for 'lib/forbear'

Synchronizing submodule url for 'lib/libaed2'

fatal: remote error: upload-pack: not our ref 24d1747e8da40c91037d6e72445a573c85748af9

fatal: the remote end hung up unexpectedly

Fetched in submodule path 'lib/forbear', but it did not contain 24d1747e8da40c91037d6e72445a573c85748af9. Direct fetching of that commit failed.
```
Checking the submodule online, this seems to be an invalid [link](https://github.com/d-vanzo/forbear/tree/24d1747e8da40c91037d6e72445a573c85748af9). Could it be that the master branch has some uncommited changes to the submodule. I was just reading this post [here](https://stackoverflow.com/questions/61163082/why-does-git-submodule-update-fail-with-fatal-remote-error-upload-pack-not-o), but I am not sure if the error is on my side or on Simstrat's github repo.

Thanks,
Robert

**Comment by f-baerenbold** [comment]
The problem should now be solved on the current master branch. Please tell us if not..
