### ISSUE TITLE
Option to turn off progress bar is needed

### ISSUE THREAD

**Issue by akesandgren** [Eawag-AppliedSystemAnalysis/Simstrat#54]
When running Simstrat through a batch system the progressbar is useless in its current form, it just produces tons of useless data in the output and fills up disk space.

The code needs an option to turn off the progress bar completely at the very least, but an option to specify its behavior would be better.
Like off/progress-report-interval-in-secs or something on those lines.

**Comment by f-baerenbold** [comment]
Thanks for the suggestion. This issue is solved with b917e4c.

The progressbar can now be switched off by specifying
"Show progress bar"           : false
in the "Simulation" block of the config file.
Please use the current master branch

**Comment by akesandgren** [comment]
Perfect, thanks.
