### ISSUE TITLE
Check for correctness of input files during initialization

### ISSUE THREAD

**Issue by adrien-ga** [Eawag-AppliedSystemAnalysis/Simstrat#6]
E.g. if the sign of the depths in the bathymetry is positive instead of negative, Simstrat crashes and writes that it cannot open the initial conditions file. As this error doesn't allow to trace back to the mistake, there have to be checks and warnings.

**Comment by adrien-ga** [comment]
If the 0 depth is missing in the bathymetry file, simstrat somehow calculates a zero volume for the basin and crashes.

**Comment by Diftin** [comment]
Agree for the negative depths. Can't reproduce the error if the 0 depth is missing. However, the result is quite different if the 0 depth is missing.

**Comment by Diftin** [comment]
I introduced an error message if the 0 (or another positive value) is missing. An error also occurs if the depths are not monotonously decreasing
