### ISSUE TITLE
C10: actual value or factor

### ISSUE THREAD

**Issue by adrien-ga** [Eawag-AppliedSystemAnalysis/Simstrat#8]
If the wind drag model is not 1, some code versions of Simstrat seem to use the C10 parameter as a calibrating factor for the wind drag relation. In my opinion, this is a bit risky. I would rather have it used only as an absolute value for the case that the wind drag model is 1.
In the new version, C10 would be required in this case, and there would be a warning in case the wind drag model is not 1, saying that the parameter will be ignored.

**Comment by Diftin** [comment]
The code now gives out an error if C10 is intended as physical parameter (wind drag model 1) but the value is too high to be physically possible. There is also an error if C10 is intended as calibration parameter (wind drag model 2 and 3) and the value is too low.
